interface=wlan0
driver=nl80211
hw_mode=g
channel=6
auth_algs=1
wmm_enabled=1

# Important stuff
ssid=WPA2_Test_WiFi
wpa_passphrase=000999888

# 802.11n Configuration
ieee80211n=1

# WPA2 Configuration
wpa=2
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
wpa_pairwise=CCMP