FROM alpine:3.21
RUN apk add --no-cache dnsmasq
ENTRYPOINT ["dnsmasq", "-k", "--no-resolv", \
    "--filter-rr=HTTPS", "--filter-rr=SVCB", "--filter-rr=AAAA", \
    "--server=1.1.1.1", "--server=8.8.8.8", \
    "--listen-address=0.0.0.0"]
