services:
  http-s-proxy:
    container_name: http-s-proxy
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    restart: unless-stopped

  dns-filter:
    container_name: dns-filter
    build:
      context: .
      dockerfile: Dockerfile.dns
    network_mode: host
    restart: unless-stopped
